name: Build android (on MacOS)

on:
  push:
    paths-ignore:
      - '.github/workflows/ios.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/mac.yml'
      - '.github/workflows/win.yml'
      - 'LICENSE'
      - 'README.md'

concurrency:
  group: ci-${{github.ref}}-android
  cancel-in-progress: true
  
jobs:
  android_build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - TRIPLET: 'arm-android'
            QT_ARCH: 'android_armv7'
          - TRIPLET: 'amd64-android'
            QT_ARCH: 'android_arm64_v8a'
                
    runs-on: macos-12
    env:
      QT_VERSION: '6.5.2'
      CMAKE_GENERATOR: "Ninja"
      ANDROIDAPI: 24
      NDK_VERSION: r25b
      NDK_VERSION_FULL: r25b
      JDK_VERSION: 11
      SDK_PLATFORM: android-33
      SDK_BUILD_TOOLS: 33.0.1
      XC_VERSION: ${{ '14.2' }}
      QT_ARCH: "android"
      VCPKG_ROOT: "/Users/runner/vcpkg"
      VCPKG_BASELINE: "d765306b074717dea8dc1c4723e1b025acb61c2d" # use scripts/update_vcpkg_base.bash to change
      CACHE_VERSION: 0

    steps:
      - uses: actions/checkout@v3
        with:
          path: input-sdk

      - name: Prepare vars
        id: vars
        run: |
          brew install automake bison flex gnu-sed autoconf-archive libtool
          echo $(brew --prefix bison)/bin >> $GITHUB_PATH
          echo $(brew --prefix flex)/bin >> $GITHUB_PATH

      - name: Setup compiler
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XC_VERSION }}

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION_FULL }}
          add-to-path: true

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
         java-version: ${{ env.JDK_VERSION }}
         distribution: zulu

      - name: Setup Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2

      - name: Install Android Tools
        run: |
          sdkmanager --licenses && sdkmanager --verbose "platforms;${SDK_PLATFORM}" "build-tools;${SDK_BUILD_TOOLS}" tools platform-tools

      - name: Install Qt (android)
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          setup-python: 'false'
          modules: 'qtsensors qtconnectivity qt5compat qtmultimedia qtpositioning qtshadertools'
          dir: ${{ github.workspace }}
          target: ${{ matrix.QT_ARCH }}
          arch: ${{ matrix.qt_arch }}
          cache: true
          cache-key-prefix: ${{ runner.os }}-QtCache-v2-${{ env.QT_VERSION }}-android
          
      - name: Install Qt (desktop)
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          setup-python: 'false'
          modules: 'qtsensors qtconnectivity qt5compat qtmultimedia qtpositioning qtshadertools'
          dir: ${{ github.workspace }}
          target: desktop
          cache: true
          cache-key-prefix: ${{ runner.os }}-QtCache-v2-${{ env.QT_VERSION }}-desktop

      - name: Restore vcpkg folder
        id: cache-vcpkg-restore
        if: ${{ github.ref != 'refs/heads/master' }} # do not use cache on master
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.VCPKG_ROOT }}
          key: VCPKG-${{ runner.os }}-${{ matrix.TRIPLET }}-v${{ env.CACHE_VERSION }}-ref-${{ github.ref }}

      - uses: actions/checkout@v3
        if: steps.cache-vcpkg-restore.outputs.cache-hit != 'true'
        with:
          repository: microsoft/vcpkg
          path: ${{ env.VCPKG_ROOT }}
          ref: ${ env.VCPKG_BASELINE }

      - name: Build Deps
        run: |
          mkdir -p ${{ github.workspace }}/build
          cd ${{ github.workspace }}/build
          cmake -B ${{ github.workspace }}/build/${{ matrix.arch }} \
                -S ${{ github.workspace }}/input-sdk \
                -DCMAKE_MODULE_PATH:PATH="${{ github.workspace }}/vcpkg-test/cmake" \
                -DCMAKE_TOOLCHAIN_FILE:PATH="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" \
                -G Ninja \
                -DVCPKG_TARGET_TRIPLET=${{ matrix.TRIPLET }} \
                -DVCPKG_OVERLAY_TRIPLETS:PATH="${{ github.workspace }}/vcpkg-overlay/triplets" \
                -DVCPKG_OVERLAY_PORTS="${{ github.workspace }}/vcpkg-overlay/ports"

      - name: Upload build logs on deps failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-logs-${{ matrix.TRIPLET }}
          path: |
            ${{ env.VCPKG_ROOT }}/buildtrees/**/*.log

      - name: Save vcpkg folder
        uses: actions/cache/save@v3
        if: always() && ${{ github.ref != 'refs/heads/master' }} # do not use cache on master; save on error too
        id: cache-vcpkg-save
        with:
          path: ${{ env.VCPKG_ROOT }}
          key: ${{ steps.cache-vcpkg-restore.outputs.cache-primary-key }}

      - name: Build Test App
        run: |
          cd ${{ github.workspace }}/build/${{ matrix.arch }}
          ninja

      - name: Get TimeStamp
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDD'

      - name: Create SDK data folder 
        run: |
            mkdir -p ${{ github.workspace }}/sdk
            cp -R ${{ github.workspace }}/build/vcpkg_installed/${{ matrix.TRIPLET }}/* ${{ github.workspace }}/sdk/*
            rm -rf ${{ github.workspace }}/sdk/debug
            rm -rf ${{ github.workspace }}/sdk/etc
            rm -rf ${{ github.workspace }}/sdk/mkspecs
            rm -rf ${{ github.workspace }}/sdk/share
            rm -rf ${{ github.workspace }}/sdk/tools
            
            SDK_TAR=mergin-maps-input-sdk-qt-${{ env.QT_VERSION }}-${{ matrix.TRIPLET }}-${{ steps.time.outputs.time }}-${{ github.run_number }}.tar.gz
            echo "SDK_TAR=${SDK_TAR}" >> $GITHUB_ENV
            
            cd ${{ github.workspace }}/sdk/
            find libs/
            tar -c -z -f ${{ github.workspace }}/${SDK_TAR} ./

      - name: Upload Sdk in Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/${{ env.SDK_TAR }}

      - name: Create Release
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TRIPLET }}-${{ steps.time.outputs.time }}-${{ github.run_number }}
          allowUpdates: true
          artifacts: ${{ env.SDK_TAR }}
          token: ${{ secrets.GITHUB_TOKEN }}
