name: Build ios

on:
  push:
    paths:
      - 'vcpkg-test/**'
      - 'vcpkg-overlay/**'
      - '.github/workflows/ios.yml'

  release:
    types:
      - published

concurrency:
  group: ci-${{github.ref}}-ios
  cancel-in-progress: true
  
jobs:
  ios_build:
    runs-on: macos-12
    env:
      IOS_MIN_SDK_VERSION: '14.0' # iOS Deployment target 
      QT_VERSION: '6.5.2'
      ARCH: 'arm64'
      CACHE_VERSION: 0
      XC_VERSION: ${{ '14.2' }}
      VCPKG_BASELINE: "d765306b074717dea8dc1c4723e1b025acb61c2d" # compatible with vcpkg.json baseline
      VCPKG_ROOT: "/Users/runner/vcpkg-root" # Looks like there is more space on C: than on D: drive (~14GB)

    steps:
      - uses: actions/checkout@v2

      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Restore cached QT
        id: cache-qt-restore
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ runner.os }}-QtCache-v${{ env.QT_CACHE_VERSION }}-qt-${{ env.QT_VERSION }}-${{ matrix.arch }}

      - name: Install Qt
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
          pip3 install -U pip
          pip3 install aqtinstall
        
          python3 -m aqt install-qt \
            mac ios ${{ env.QT_VERSION }} \
            -m qtsensors qtconnectivity qt5compat qtmultimedia qtpositioning qtshadertools \
            -O ${{ github.workspace }}/Qt
            
          python3 -m aqt install-qt \
            mac desktop ${{ env.QT_VERSION }} \
            -m qtsensors qtconnectivity qt5compat qtmultimedia qtpositioning qtshadertools \
            -O ${{ github.workspace }}/Qt

          ls -la ${{ github.workspace }}/Qt/${{ env.QT_VERSION }}

      - name: Save cached Qt
        uses: actions/cache/save@v3
        if: always()
        id: cache-qt-save
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ runner.os }}-QtCache-v${{ env.QT_CACHE_VERSION }}-qt-${{ env.QT_VERSION }}-${{ matrix.arch }}

      - name: Restore cached vcpkg build folder
        id: cache-vcpkg-restore
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.VCPKG_ROOT }}/${{ env.ARCH }}
          key: ${{ runner.os }}-vcpkg-v${{ env.CACHE_VERSION }}-qt-${{ env.QT_VERSION }}-${{ env.ARCH }}

      - name: Clone vcpkg
        if: steps.cache-vcpkg-restore.outputs.cache-hit != 'true'
        run: |
          mkdir -p "${{ env.VCPKG_ROOT }}"
          cd "${{ env.VCPKG_ROOT }}"
          git init
          git remote add origin https://github.com/microsoft/vcpkg.git
          git pull origin master
          git checkout $VCPKG_BASELINE

      - name: Build SDK ${{ env.ARCH }}-ios
        run: |
          mkdir -p ${{ github.workspace }}/build/${{ env.ARCH }}
          cd ${{ github.workspace }}/build/${{ env.ARCH }}
          cmake -B ${{ github.workspace }}/build/${{ env.ARCH }} \
                -S ${{ github.workspace }}/vcpkg-test \
                -DCMAKE_MODULE_PATH:PATH="${{ github.workspace }}/vcpkg-test/cmake" \
                -DCMAKE_TOOLCHAIN_FILE:PATH="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" \
                -G Ninja \
                -DVCPKG_TARGET_TRIPLET=${{ env.ARCH }}-ios \
                -DVCPKG_OVERLAY_TRIPLETS:PATH="${{ github.workspace }}/vcpkg-overlay/triplets" \
                -DVCPKG_OVERLAY_PORTS="${{ github.workspace }}/vcpkg-overlay/ports"

      - name: Upload build logs on deps failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-logs-${{ env.ARCH }}-ios
          path: |
            ${{ env.VCPKG_ROOT }}/buildtrees/**/*.log

      - name: Save cached vcpkg build folder
        uses: actions/cache/save@v3
        if: always()
        id: cache-vcpkg-save
        with:
          path: ${{ env.VCPKG_ROOT }}/${{ env.ARCH }}
          key: ${{ runner.os }}-vcpkg-v${{ env.CACHE_VERSION }}-qt-${{ env.QT_VERSION }}-${{ env.ARCH }}

      - name: Build Test App
        run: |
          cd ${{ github.workspace }}/build/${{ env.ARCH }}
          ninja

      - name: Get TimeStamp
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDD'

      - name: Create package
        run: |
          SDK_TAR=input-sdk-qt-${{ env.QT_VERSION }}-ios-${{ steps.time.outputs.time }}-${{ github.run_number }}.tar.gz
          echo "SDK_TAR=${SDK_TAR}" >> $GITHUB_ENV
          cd "${{ github.workspace }}/build/stage"
          tar -c -z --exclude=*.pyc -f ${{ github.workspace }}/${SDK_TAR} ./

      - name: Upload Sdk in Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/${{ env.SDK_TAR }}

      - name: Create Release
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ios-${{ steps.time.outputs.time }}-${{ github.run_number }}
          allowUpdates: true
          artifacts: ${{ env.SDK_TAR }}
          token: ${{ secrets.GITHUB_TOKEN }}
