name: Build ios

on:
  push:
    paths-ignore:
      - '.github/workflows/android.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/mac.yml'
      - '.github/workflows/win.yml'
      - 'LICENSE'
      - 'README.md'

concurrency:
  group: ci-${{github.ref}}-ios
  cancel-in-progress: true
  
jobs:
  ios_build:
    runs-on: macos-12
    env:
      QT_VERSION: '6.5.2'
      TRIPLET: "arm64-ios"
      DEPLOYMENT_TARGET: '14.0' # iOS Deployment target 
      XC_VERSION: ${{ '14.2' }}
      QT_ARCH: "ios"
      VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
      VCPKG_BASELINE: "d765306b074717dea8dc1c4723e1b025acb61c2d" # use scripts/update_vcpkg_base.bash to change

    steps:
      - uses: actions/checkout@v3
        with:
          path: input-sdk

      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"

      - name: Prepare vars
        id: vars
        run: |
          brew install automake bison flex gnu-sed autoconf-archive libtool gettext cmake ninja
          echo $(brew --prefix bison)/bin >> $GITHUB_PATH
          echo $(brew --prefix flex)/bin >> $GITHUB_PATH
          echo $(brew --prefix gettext)/bin >> $GITHUB_PATH

          pip3 install -U pip
          pip3 install aqtinstall

      - name: Install Qt (ios)
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          setup-python: 'false'
          modules: 'qtsensors qtconnectivity qt5compat qtmultimedia qtpositioning qtshadertools'
          dir: ${{ github.workspace }}
          target: ${{ env.QT_ARCH }}
          arch: ${{ matrix.qt_arch }}
          
      - name: Install Qt (desktop)
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          setup-python: 'false'
          modules: 'qtsensors qtconnectivity qt5compat qtmultimedia qtpositioning qtshadertools'
          dir: ${{ github.workspace }}
          target: desktop
          set-env: false

      - name: Get vcpkg
        if: steps.cache-vcpkg-restore.outputs.cache-hit != 'true'
        shell: bash
        run: |
          mkdir -p "${{ env.VCPKG_ROOT }}"
          cd "${{ env.VCPKG_ROOT }}"
          git init
          git remote add origin https://github.com/microsoft/vcpkg.git
          git pull origin master
          git checkout $VCPKG_BASELINE

          echo "install vcpkg"
          chmod +x ./bootstrap-vcpkg.sh
          ./bootstrap-vcpkg.sh
          ./vcpkg --version

      - name: Build Deps
        run: |
          mkdir -p ${{ github.workspace }}/build
          cd ${{ github.workspace }}/build
          
          echo "Qt6_HOST_Dir=${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/macos" >> $GITHUB_ENV
          echo "PATH=${{ env.VCPKG_ROOT }}:$PATH" >> $GITHUB_ENV
          
          ./vcpkg --version
          ls -l ${Qt6_HOST_Dir}/../
          
          cmake -B ${{ github.workspace }}/build \
                -S ${{ github.workspace }}/input-sdk \
                -DCMAKE_TOOLCHAIN_FILE:PATH="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" \
                -G Ninja \
                -DVCPKG_TARGET_TRIPLET=${{ env.TRIPLET }} \
                -DVCPKG_OVERLAY_TRIPLETS:PATH="${{ github.workspace }}/input-sdk/vcpkg-overlay/triplets" \
                -DVCPKG_OVERLAY_PORTS="${{ github.workspace }}/input-sdk/vcpkg-overlay/ports" \
                -D CMAKE_SYSTEM_NAME=iOS \
                -D CMAKE_SYSTEM_PROCESSOR=aarch64 \
                -D CMAKE_OSX_DEPLOYMENT_TARGET=${{ env.DEPLOYMENT_TARGET }} \
                -D ENABLE_BITCODE=OFF \
                -D ENABLE_ARC=ON \
                -D CMAKE_CXX_VISIBILITY_PRESET=hidden \
                -DCMAKE_MAKE_PROGRAM=ninja
                

      - name: Upload build logs on deps failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-logs-${{ env.TRIPLET }}
          path: |
            ${{ env.VCPKG_ROOT }}/buildtrees/**/*.log

      - name: Build Test App
        run: |
          cd ${{ github.workspace }}/build
          ninja

      - name: Get TimeStamp
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDD'

      - name: Create SDK data folder 
        run: |
            mkdir -p ${{ github.workspace }}/sdk
            cp -R ${{ github.workspace }}/build/vcpkg_installed/${{ env.TRIPLET }}/* ${{ github.workspace }}/sdk/*
            rm -rf ${{ github.workspace }}/sdk/debug
            rm -rf ${{ github.workspace }}/sdk/etc
            rm -rf ${{ github.workspace }}/sdk/mkspecs
            rm -rf ${{ github.workspace }}/sdk/share
            rm -rf ${{ github.workspace }}/sdk/tools
            
            SDK_TAR=mergin-maps-input-sdk-qt-${{ env.QT_VERSION }}-${{ env.TRIPLET }}-${{ steps.time.outputs.time }}-${{ github.run_number }}.tar.gz
            echo "SDK_TAR=${SDK_TAR}" >> $GITHUB_ENV
            
            cd ${{ github.workspace }}/sdk/
            find libs/
            tar -c -z -f ${{ github.workspace }}/${SDK_TAR} ./

      - name: Upload Sdk in Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/${{ env.SDK_TAR }}

      - name: Create Release
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TRIPLET }}-${{ steps.time.outputs.time }}-${{ github.run_number }}
          allowUpdates: true
          artifacts: ${{ env.SDK_TAR }}
          token: ${{ secrets.GITHUB_TOKEN }}
