name: Build Linux

on:
  push:
    paths:	
      - 'linux/**'
      - '.github/workflows/linux.yml'
      - 'versions.conf'
  release:
    types:
      - published

jobs:
  linux_build:
    runs-on: ubuntu-20.04
    if: github.repository == 'lutraconsulting/input-sdk'
    env:
      ARCH: 'linux-x86_64'
      CACHE_VERSION: 1

    steps:
      - uses: actions/checkout@v2

      - name: Prepare build cache for branch/tag
        # use a fork of actions/cache@v2 to upload cache even when the build or test failed
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ${{ github.workspace }}/build
          # The branch or tag ref that triggered the workflow run. For branches this in the format refs/heads/<branch_name>, and for tags it is refs/tags/<tag_name>
          key: cache-v${{ env.CACHE_VERSION }}-${{ env.QT_VERSION }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            cache-v${{ env.CACHE_VERSION }}-${{ env.QT_VERSION }}-${{ github.ref }}-
            cache-v${{ env.CACHE_VERSION }}-${{ env.QT_VERSION }}-refs/heads/master-

      - name: Install Build Dependencies
        run: |
            sudo apt-get install -y qtpositioning5-dev qml-module-qtmultimedia qml-module-qtpositioning \
                                    qml-module-qtqml-models2 qml-module-qtgraphicaleffects qml-module-qtquick-dialogs \
                                    qml-module-qtquick-controls2 qml-module-qtquick-window2 qml-module-qtquick-layouts \
                                    qml-module-qtquick-shapes qml-module-qtquick-controls qtquickcontrols2-5-dev \
                                    libqt5sensors5-dev qtmultimedia5-dev
            sudo apt-get install qml-module-qt-labs-*
            sudo apt install sqlite3

      - name: Export config.conf
        run: |
          touch ./linux/config.conf
          echo -e "export ROOT_OUT_PATH=${{ github.workspace }}/build"  >> ./linux/config.conf
          echo -e "export ARCHES=("\""${{ env.ARCH }}"\"")"  >> ./linux/config.conf
          cat ./linux/config.conf

      - name: Build Sdk
        run: |
          ./mac/distribute.sh -mqgis
 
      - name: Get TimeStamp
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDD'

      - name: Create package
        run: |
          SDK_TAR=input-sdk-qt-${{ env.QT_VERSION }}-linux-${{ steps.time.outputs.time }}-${{ github.run_number }}.tar.gz
          echo "SDK_TAR=${SDK_TAR}" >> $GITHUB_ENV
          cd "${{ github.workspace }}/build/stage/${{ env.ARCH }}"
          tar -c -z -f ${{ github.workspace }}/${SDK_TAR} ./

      - name: Upload Sdk in Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/${{ env.SDK_TAR }}

      - name: Create Release
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: ncipollo/release-action@v1
        with:
          tag: mac-${{ steps.time.outputs.time }}-${{ github.run_number }}
          allowUpdates: true
          artifacts: ${{ env.SDK_TAR }}
          token: ${{ secrets.GITHUB_TOKEN }}
