name: Build macOS

on:
  push:
    paths-ignore:
      - '.github/workflows/android.yml'
      - '.github/workflows/ios.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/win.yml'
      - 'LICENSE'
      - 'README.md'

concurrency:
  group: ci-${{github.ref}}-mac
  cancel-in-progress: true

jobs:
  mac_os_build:
    runs-on: macos-12
    if: github.repository == 'merginmaps/input-sdk'

    env:
      QT_VERSION: '6.5.2'
      TRIPLET: "x64-osx"
      DEPLOYMENT_TARGET: 10.15.0
      XC_VERSION: ${{ '14.2' }}
      QT_ARCH: "desktop"
      VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
      VCPKG_BASELINE: "d765306b074717dea8dc1c4723e1b025acb61c2d" # use scripts/update_vcpkg_base.bash to change
      CACHE_VERSION: 1
    
    steps:
      - uses: actions/checkout@v3
        with:
          path: input-sdk

      - name: Prepare vars
        id: vars
        run: |
          brew install automake bison flex gnu-sed autoconf-archive libtool gettext cmake ninja
          echo $(brew --prefix bison)/bin >> $GITHUB_PATH
          echo $(brew --prefix flex)/bin >> $GITHUB_PATH
          echo $(brew --prefix gettext)/bin >> $GITHUB_PATH

      - uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          setup-python: 'false'
          target: ${{ env.QT_ARCH }}
          dir: ${{ github.workspace }}
          modules: 'qtsensors qtconnectivity qt5compat qtmultimedia qtpositioning qtshadertools'
          cache: true
          cache-key-prefix: ${{ runner.os }}-QtCache-v1-${{ env.QT_VERSION }}-mac

      - name: Setup compiler
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XC_VERSION }}

      - name: Get vcpkg
        shell: bash
        run: |
          mkdir -p "${{ env.VCPKG_ROOT }}"
          cd "${{ env.VCPKG_ROOT }}"
          git init
          git remote add origin https://github.com/microsoft/vcpkg.git
          git pull origin master
          git checkout $VCPKG_BASELINE

      - name: Install vcpkg
        run: |
          echo "install vcpkg"
          cd "${{ env.VCPKG_ROOT }}"
          chmod +x ./bootstrap-vcpkg.sh
          ./bootstrap-vcpkg.sh

      - name: Build Deps
        run: |
          mkdir -p ${{ github.workspace }}/build
          cd ${{ github.workspace }}/build
          
          export PATH=${{ env.VCPKG_ROOT }}:$PATH

          vcpkg --version
          ls -l ${Qt6_DIR}/lib
          
          cmake -B ${{ github.workspace }}/build \
                -S ${{ github.workspace }}/input-sdk \
                -DCMAKE_TOOLCHAIN_FILE:PATH="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" \
                -GNinja \
                -DVCPKG_TARGET_TRIPLET=${{ env.TRIPLET }} \
                -DVCPKG_OVERLAY_TRIPLETS:PATH="${{ github.workspace }}/input-sdk/vcpkg-overlay/triplets" \
                -DVCPKG_OVERLAY_PORTS="${{ github.workspace }}/input-sdk/vcpkg-overlay/ports" \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_MAKE_PROGRAM=ninja

      - name: Upload build logs on deps failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-logs-${{ env.TRIPLET }}
          path: |
            ${{ env.VCPKG_ROOT }}/buildtrees/**/*.log

      - name: Build Test App
        run: |
          cd ${{ github.workspace }}/build
          ninja

      - name: Run Tests
        run: |
          cd ${{ github.workspace }}/build
          ./merginmapsinputsdk

      - name: Get TimeStamp
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDD'

      - name: Create GDAL supported formats 
        run: |
            ${{ github.workspace }}/build/vcpkg_installed/${{ env.TRIPLET }}/tools/gdal/gdalinfo --formats | tee -a ${{ github.workspace }}/supported_formats.log
            ${{ github.workspace }}/build/vcpkg_installed/${{ env.TRIPLET }}/tools/gdal/ogrinfo --formats | tee -a ${{ github.workspace }}/supported_formats.log
            
            SUPPORTED_FORMATS="mergin-maps-input-sdk-gdal-supported-formats-${{ steps.time.outputs.time }}-${{ github.run_number }}.log"
            echo "SUPPORTED_FORMATS=${SUPPORTED_FORMATS}" >> $GITHUB_ENV
            
            cat ${{ github.workspace }}/supported_formats.log

      - name: Create PROJ data folder 
        run: |
            mkdir -p ${{ github.workspace }}/proj-data
            echo ".. 1/2 qgis database"
            mkdir -p ${{ github.workspace }}/proj-data/resources
            ${{ github.workspace }}/build/vcpkg_installed/${{ env.TRIPLET }}/share/qgis/proj/qgis.db ${{ github.workspace }}/proj-data/resources/
            ${{ github.workspace }}/build/vcpkg_installed/${{ env.TRIPLET }}/share/qgis/proj/srs.db ${{ github.workspace }}/proj-data/resources/
            echo ".. 2/2 proj resources"
            mkdir -p ${{ github.workspace }}/proj-data/proj
            ${{ github.workspace }}/build/vcpkg_installed/${{ env.TRIPLET }}/share/proj/* ${{ github.workspace }}/proj-data/proj/
            
            PROJ_TAR=mergin-maps-input-sdk-proj-mac-${{ steps.time.outputs.time }}-${{ github.run_number }}.tar.gz
            echo "PROJ_TAR=${PROJ_TAR}" >> $GITHUB_ENV
            
            cd "${{ github.workspace }}/proj-data"
            find ./
            tar -c -z -f ${{ github.workspace }}/${PROJ_TAR} ./


      - name: Create SDK data folder 
        run: |
            mkdir -p ${{ github.workspace }}/sdk
            cp -R ${{ github.workspace }}/build/vcpkg_installed/${{ env.TRIPLET }}/* ${{ github.workspace }}/sdk/*
            rm -rf ${{ github.workspace }}/sdk/debug
            rm -rf ${{ github.workspace }}/sdk/etc
            rm -rf ${{ github.workspace }}/sdk/mkspecs
            rm -rf ${{ github.workspace }}/sdk/share
            rm -rf ${{ github.workspace }}/sdk/tools
            
            SDK_TAR=mergin-maps-input-sdk-qt-${{ env.QT_VERSION }}-${{ env.TRIPLET }}-${{ steps.time.outputs.time }}-${{ github.run_number }}.tar.gz
            echo "SDK_TAR=${SDK_TAR}" >> $GITHUB_ENV
            
            cd ${{ github.workspace }}/sdk/
            find libs/
            tar -c -z -f ${{ github.workspace }}/${SDK_TAR} ./

      - name: Upload SDK_TAR artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/${{ env.SDK_TAR }}
          if-no-files-found: error    

      - name: Upload SUPPORTED_FORMATS artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/${{ env.SUPPORTED_FORMATS }} 
          if-no-files-found: error 
          
      - name: Upload PROJ_TAR artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/${{ env.PROJ_TAR }} 
          if-no-files-found: error 

      - name: Create Release
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TRIPLET }}-${{ steps.time.outputs.time }}-${{ github.run_number }}
          allowUpdates: true
          artifacts: "${{ env.SDK_TAR }},${{ env.SUPPORTED_FORMATS }},${{ env.PROJ_TAR }}"
          token: ${{ secrets.GITHUB_TOKEN }}
